name: Documentation
description: You know words. You have the best words. And you'd like to make sure we have the best words too.
labels: documentation

body:
  - type: textarea
    attributes:
      label: Documentation
      description: >-
        Please describe the issue with the current documentation and what it
        should be changed to.
    validations:
      required: true

  - type: input
    attributes:
      label: Priority
      description: >-
        How pressing is this issue?
    validations:
      required: true